[package]
name = "thrash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt = "0.14.0"
clap = { version = "4.1.4", features = ["derive"] }
itertools = "0.10.5"
md5 = "0.7.0"
rayon = "1.6.1"
